version: '3.8'
services:
  enfercuidarte_back_end:
    build: .
    command: node dist/index.js
    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'
    depends_on:
      - enfercuidarte_MySQL
    env_file:
      - .env
  enfercuidarte_MySQL:
    image: mysql
    ports:
      - 3500:3306
    env_file:
      - .env.db
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
